OLED_ENABLE = yes
OLED_DRIVER = SSD1306

RGBLIGHT_ENABLE = yes        # Enable RGBLIGHT
RGBLIGHT_DRIVER = WS2812
RGB_MATRIX_ENABLE = no      # Enable RGB_MATRIX (not work yet)
RGB_MATRIX_DRIVER = WS2812

CONSOLE_ENABLE = yes